version: '2.0'

networks:
  default:
    driver: bridge

services:
  api:
    container_name: movies-api
    build: .
    ports:
      - '80:3000'
    environment:
      NODE_ENV: local
      JWT_SECRET: ed689a8a16e0f0a32ebe030b4548c45307dbdf442587779ebe98df857c4ced81
      TZ: America/Sao_Paulo
      DB_HOST: postgres
      DB_PORT: 5435
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: movies
      REDIS_URL: redis:6379

    networks:
      - default

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies

    ports:
      - "5435:5435"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - default