version: '2.0'

networks:
  default:
    driver: bridge

services:
  api:
    container_name: movies-api
    build: .
    ports:
      - '80:3000'
    env_file:
      - .env.example
    networks:
      - default

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies

    ports:
      - "5435:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - default